### ISSUE TITLE
What about macOS version ?

### ISSUE THREAD

**Issue by azoreseuropa** [ogamespec/dolwin#72]
I know how to build some emulators. What tools do I need to build it for macOs ? I want to test it.

**Comment by ogamespec** [comment]
Sorry, Windows only :) But you can clone the source code and do whatever you want.

**Comment by azoreseuropa** [comment]
I understand. No problem but just want to see if it can be done. Dolwin would be nice for macOS as addition for macOS users who dont have windows, you know. The problem is how to compile. I type git clone and use your source then type cd dolwin then mkdir build && cd build
then what's next ? Dont know about yours. I try cmake .. and I got an error. Thats halt for the next one. Need further.

**Comment by ogamespec** [comment]
This topic is beyond current state of development. There are more important tasks, they are listed in milestones. In addition, Dolwin does not have build scripts for OSes other than Windows.

Each component of the emulator contains a Scripts folder, there you can place the Makefile for build in other OSes.

I will not close the issue, you can discuss here and further or on our Discord channel.

**Comment by azoreseuropa** [comment]
I understand. That's alright, I have Windows as well. Just want to see how it is goes for macOs. That doesn't matter now. I shall close it anyway. I thank you for your time to read and answered my questions. Much appreciated and keep up the good work. I like dolwin as much as dolphin. Glad to see that it is resurrected from the dead. Cheers!

**Comment by spotanjo3** [comment]
How is it going ? Is macOS now working with this emulator ? Curiosity since almost one year today.

**Comment by ogamespec** [comment]
There is no one to do this :)
